// search index for WYSIWYG Web Builder
var database_length = 0;

function SearchPage(url, title, keywords, description)
{
   this.url = url;
   this.title = title;
   this.keywords = keywords;
   this.description = description;
   return this;
}

function SearchDatabase()
{
   database_length = 0;
   this[database_length++] = new SearchPage("home.html", "XXTREP Repository", "xxtrep repository translation suggestions pull nbsp requests supported platforms how to install code borrowing contacts what is kodi? problem with posters on aeon mq6 view github quick answers search copyright by taifxxthis program free software you can redistribute it and or modify under the terms of gnu general public license as published foundation either version at your option any later this distributed in hope that will be useful but without warranty even implied merchantability fitness for particular purpose see more details http www org licenses add ons from kodi taifxx download language russian home lib about information launchers faq forums xbmc ru tv downloads gt make easy ", "");
   this[database_length++] = new SearchPage("downloads.html", "XXTREP: Downloads", "xxtrep downloads translation suggestions pull nbsp requests supported platforms how to install code borrowing contacts what is kodi? problem with posters on aeon mq6 view github quick answers search copyright by taifxxthis program free software you can redistribute it and or modify under the terms of gnu general public license as published foundation either version at your option any later this distributed in hope that will be useful but without warranty even implied merchantability fitness for particular purpose see more details http www org licenses repository add ons recomended tar gz zip githubadd lib atl backup launcheratl update launcher from kodi taifxx download language russian home about information launchers faq forums xbmc ru tv gt make easy ", "");
   this[database_length++] = new SearchPage("forums.html", "XXTREP: Forums", "xxtrep forums translation suggestions pull nbsp requests supported platforms how to install code borrowing contacts what is kodi? problem with posters on aeon mq6 view github quick answers search copyright by taifxxthis program free software you can redistribute it and or modify under the terms of gnu general public license as published foundation either version at your option any later this distributed in hope that will be useful but without warranty even implied merchantability fitness for particular purpose see more details http www org licenses add lib xbmc ru kodi tv ons from repository taifxx download language russian home about information launchers faq downloads gt make easy ", "");
   this[database_length++] = new SearchPage("_Blank.html", "Untitled Page", "untitled page translation suggestions pull nbsp requests supported platforms how to install code borrowing contacts what is kodi? problem with posters on aeon mq6 view github quick answers search copyright by taifxxthis program free software you can redistribute it and or modify under the terms of gnu general public license as published foundation either version at your option any later this distributed in hope that will be useful but without warranty even implied merchantability fitness for particular purpose see more details http www org licenses add ons from xxtrep kodi repository taifxx download language russian home lib about information launchers faq forums xbmc ru tv downloads gt make easy ", "");
   this[database_length++] = new SearchPage("addtolib/addtolib-about.html", "XXTREP: ADD TO Lib - About", "xxtrep add to lib about translation suggestions pull nbsp requests supported platforms how install code borrowing contacts what is kodi? problem with posters on aeon mq6 view github quick answers search copyright by taifxxthis program free software you can redistribute it and or modify under the terms of gnu general public license as published foundation either version at your option any later this distributed in hope that will be useful but without warranty even implied merchantability fitness for particular purpose see more details http www org licenses kodicontext menu item links tv shows movies from other ons kodi library strm files addition allows check new episodes seasons manage added content receive full information playable gt download repository recomend context addtolib zip online video contentfrom another onsto entire seasonat once watch episodesautomatically get notifiedabout sync devices using dropbox andupdates contentusing all ofscraper screenshots taifxx language russian home launchers faq forums xbmc ru downloads make easy ", "");
   this[database_length++] = new SearchPage("addtolib/addtolib-more.html", "XXTREP: ADD TO Lib - More information", "xxtrep add to lib more information translation suggestions pull nbsp requests supported platforms how install code borrowing contacts what is kodi? problem with posters on aeon mq6 view github quick answers search copyright by taifxxthis program free software you can redistribute it and or modify under the terms of gnu general public license as published foundation either version at your option any later this distributed in hope that will be useful but without warranty even implied merchantability fitness for particular purpose see details http www org licenses ons from kodi repository taifxx download language russian home about launchers faq forums xbmc ru tv downloads gt make easy ", "");
   this[database_length++] = new SearchPage("addtolib/sred-mp1.html", "XXTREP: ADD TO Lib - More information", "xxtrep add to lib more information nbsp gt this program is free software you can redistribute it and or modify under the terms of gnu general public license as published by foundation either version at your option any later about on links tv shows movies kodi video library from other ons local added videos creates episodes strm files places them in folders scanned scraper after that see categories with posters fanart watched status etc additional features for when new exists show automatically source link folder which scan report manually be seasons containing list case will presence season lt prev next ", "");
   this[database_length++] = new SearchPage("addtolib/sred-mp2.html", "XXTREP: ADD TO Lib - More information", "xxtrep add to lib more information playback control in this on is realized the possibility of obtaining full from library for playable strm files posters fan art progress etc feature when you start system launches addon sync starting with version allows video database and watched statuses dropbox thus multiple remotely located devices unable change without server nbsp lt prev next gt ", "");
   this[database_length++] = new SearchPage("addtolib/sred-mp3.html", "XXTREP: ADD TO Lib - More information", "xxtrep add to lib more information you can enable or disable this feature in the on settings if want receive about currently playing movie episode but do not use storing of current position and watched status may increase load processor playback control nbsp when option callable url there is no change into previously created strm files create new with simple by restore tv show all shows menu items other actions exists displays list added via select he becomes re index rescan for inner table links allowing define from source link title lost episodes event accidental deletion rename type open allows go folder replace already actual useful case within advanced season stable operation physically remove tools lt prev next gt ", "");
   this[database_length++] = new SearchPage("addtolib/addtolib-faq.html", "XXTREP: ADD TO Lib - F.A.Q.", "xxtrep add to lib translation suggestions pull nbsp requests supported platforms how install code borrowing contacts what is kodi? problem with posters on aeon mq6 view github quick answers search copyright by taifxxthis program free software you can redistribute it and or modify under the terms of gnu general public license as published foundation either version at your option any later this distributed in hope that will be useful but without warranty even implied merchantability fitness for particular purpose see more details http www org licenses problems launching key use launchers core using playback types ons from kodi repository taifxx download language russian home about information faq forums xbmc ru tv downloads gt make easy ", "");
   this[database_length++] = new SearchPage("addtolib/sred-aeon.html", "XXTREP: ADD TO Lib - F.A.Q.", "xxtrep add to lib the problem is that aeon mq6 taken poster exclusively from fanart in on transferring listitem element which plays setresolvedurl function kodi there small bug regarding ignores setart thus make see posters only by making adjustments skin code file nbsp addons aeonmq6 includesvariables xmlblock lt variable name quot value thumbfullscreen gt condition isempty player art thumb info it after other before closing block lazy do now fixed xml version with ", "");
   this[database_length++] = new SearchPage("addtolib/sred-launch.html", "XXTREP: ADD TO Lib - F.A.Q.", "xxtrep add to lib if you need can start by key for this use keymap editor or other launcher example launch on select edit gt global ons lib2 and press the desired within five seconds3 back three times saveother any which runs execute code runaddon context addtolib launching ", "");
   this[database_length++] = new SearchPage("addtolib/sred-launch2.html", "XXTREP: ADD TO Lib - F.A.Q.", "xxtrep add to lib repository included two script ons nbsp atl update launcher backup launcherif you need can start it using keymap editor just like on or any which runs the execute code for action runscript special home addons context addtolib py other actions id hereother use runaddon how launchers amp ", "");
   this[database_length++] = new SearchPage("addtolib/sred-launchID.html", "Безымянная страница", "Безымянная страница id for other actions nbsp update video library clean reset path to default start lt system only gt menu color selection source renamer backup remove all backups restore in automatic mode skin dropbox connection wizard disconnect delete access token synchronization db watched statuses stop services ", "");
   this[database_length++] = new SearchPage("addtolib/sred-core.html", "XXTREP: ADD TO Lib - F.A.Q.", "xxtrep add to lib typically for most users leave the player core in on settings as default if user modified playcorefactory xml then change makes sense all playback types except alternate changes only affects interaction of and has changed he had problems with control module than it is necessary set additionally uses certain play this you need choose type specify desired not list must select custom number manually nbsp wrong may result an error auto available kodi videoplayer using alternative color ", "");
   this[database_length++] = new SearchPage("addtolib/sred-pbt.html", "XXTREP: ADD TO Lib - F.A.Q.", "xxtrep add to lib playback modes are used work with addons that do not support the standard classic method of playing for example attempting launch window appears open stream you see black screen and interface freezes plays wrong file etc in on settings type as default nbsp should be selected predefined this case if is already addon source system will automatically start prompts user select option autodetect allow try determine appropriate during might freeze seconds alternative types play an may resolve some problems launching problem isp internal player allows it noted information about media content title cover roles transferred from foldef using but allowing choice movie series library folder link need tv run mode use forced adding itself typically most users leave core uses modified playcorefactory xml then change makes sense all except alternate changes only affects interaction has changed he had control module than necessary set additionally certain choose specify desired list must custom number manually color result error auto available kodi videoplayer ", "");
   this[database_length++] = new SearchPage("addtolib/addtolib-index.html", "XXTREP: ADD TO Lib", "xxtrep add to lib translation suggestions pull nbsp requests supported platforms how install code borrowing contacts what is kodi? problem with posters on aeon mq6 view github quick answers search copyright by taifxxthis program free software you can redistribute it and or modify under the terms of gnu general public license as published foundation either version at your option any later this distributed in hope that will be useful but without warranty even implied merchantability fitness for particular purpose see more details http www org licenses about information launchers ons from kodi repository taifxx download language russian home faq forums xbmc ru tv downloads gt make easy ", "");
   this[database_length++] = new SearchPage("addtolib/addtolib-launch.html", "XXTREP: ADD TO Lib - About", "xxtrep add to lib about translation suggestions pull nbsp requests supported platforms how install code borrowing contacts what is kodi? problem with posters on aeon mq6 view github quick answers search copyright by taifxxthis program free software you can redistribute it and or modify under the terms of gnu general public license as published foundation either version at your option any later this distributed in hope that will be useful but without warranty even implied merchantability fitness for particular purpose see more details http www org licenses launchersyou need launchers scripts keymap editor launching update backup actions keys from repository atl launcher editor? information faq gt download recomend ons kodi taifxx language russian home forums xbmc ru tv downloads make easy ", "");
   this[database_length++] = new SearchPage("index.html", "XXTREP", "xxtrep ", "");
   return this;
}
