// search index for WYSIWYG Web Builder
var database_length = 0;

function SearchPage(url, title, keywords, description)
{
   this.url = url;
   this.title = title;
   this.keywords = keywords;
   this.description = description;
   return this;
}

function SearchDatabase()
{
   database_length = 0;
   this[database_length++] = new SearchPage("home.html", "XXTREP Repository", "xxtrep repository translation suggestions pull nbsp requests supported platforms how to install code borrowing contacts what is kodi? problem with posters on aeon mq6 view github quick answers search copyright by taifxxthis program free software you can redistribute it and or modify under the terms of gnu general public license as published foundation either version at your option any later this distributed in hope that will be useful but without warranty even implied merchantability fitness for particular purpose see more details http www org licenses add ons from kodi taifxx download language russian home lib about information faq forums xbmc ru tv downloads ", "");
   this[database_length++] = new SearchPage("downloads.html", "XXTREP: Downloads", "xxtrep downloads translation suggestions pull nbsp requests supported platforms how to install code borrowing contacts what is kodi? problem with posters on aeon mq6 view github quick answers search copyright by taifxxthis program free software you can redistribute it and or modify under the terms of gnu general public license as published foundation either version at your option any later this distributed in hope that will be useful but without warranty even implied merchantability fitness for particular purpose see more details http www org licenses repository add ons recomended tar gz zip githubadd lib from kodi taifxx download language russian home about information faq forums xbmc ru tv ", "");
   this[database_length++] = new SearchPage("forums.html", "XXTREP: Forums", "xxtrep forums translation suggestions pull nbsp requests supported platforms how to install code borrowing contacts what is kodi? problem with posters on aeon mq6 view github quick answers search copyright by taifxxthis program free software you can redistribute it and or modify under the terms of gnu general public license as published foundation either version at your option any later this distributed in hope that will be useful but without warranty even implied merchantability fitness for particular purpose see more details http www org licenses add lib xbmc ru kodi tv ons from repository taifxx download language russian home about information faq downloads ", "");
   this[database_length++] = new SearchPage("_Blank.html", "Untitled Page", "untitled page translation suggestions pull nbsp requests supported platforms how to install code borrowing contacts what is kodi? problem with posters on aeon mq6 view github quick answers search copyright by taifxxthis program free software you can redistribute it and or modify under the terms of gnu general public license as published foundation either version at your option any later this distributed in hope that will be useful but without warranty even implied merchantability fitness for particular purpose see more details http www org licenses add ons from xxtrep kodi repository taifxx download language russian home lib about information faq forums xbmc ru tv downloads ", "");
   this[database_length++] = new SearchPage("addtolib/addtolib-about.html", "XXTREP: ADD TO Lib - About", "xxtrep add to lib about translation suggestions pull nbsp requests supported platforms how install code borrowing contacts what is kodi? problem with posters on aeon mq6 view github quick answers search copyright by taifxxthis program free software you can redistribute it and or modify under the terms of gnu general public license as published foundation either version at your option any later this distributed in hope that will be useful but without warranty even implied merchantability fitness for particular purpose see more details http www org licenses kodicontext menu item links tv shows movies from other ons kodi library strm files addition allows check new episodes seasons manage added content receive full information playable gt download repository recomend context addtolib zip online video contentfrom another onsusing entire seasonat once watch seasonsautomatically get notifiedabout availability newepisodes all showsat resources andupdates contentusing ofscraper screenshots taifxx language russian home faq forums xbmc ru downloads ", "");
   this[database_length++] = new SearchPage("addtolib/addtolib-more.html", "XXTREP: ADD TO Lib - More information", "xxtrep add to lib more information translation suggestions pull nbsp requests supported platforms how install code borrowing contacts what is kodi? problem with posters on aeon mq6 view github quick answers search copyright by taifxxthis program free software you can redistribute it and or modify under the terms of gnu general public license as published foundation either version at your option any later this distributed in hope that will be useful but without warranty even implied merchantability fitness for particular purpose see details http www org licenses ons from kodi repository taifxx download language russian home about faq forums xbmc ru tv downloads ", "");
   this[database_length++] = new SearchPage("addtolib/sred-mp1.html", "XXTREP: ADD TO Lib - More information", "xxtrep add to lib more information nbsp library kodi on this program is free software you can redistribute it and or modify under the terms of gnu general public license as published by foundation either version at your option any later about links tv shows movies in video from other ons creates episodes strm files places them folders need focuses playable link movie file be folder containing show season open context menu use item into local default path lt home gt userdata addon data addtolib change names settings must one time sources choose scrapers for adding select after action will added prev next ", "");
   this[database_length++] = new SearchPage("addtolib/sred-mp2.html", "XXTREP: ADD TO Lib - More information", "xxtrep add to lib more information adding episodes season the nbsp tv show you need be in folder containing playable links files open context menu of any and select on library as when was able determine name this has exists will added an existing item update is used new from source already or automatically link which can scan report about one may include plurality sources are managed management for manually seasons list case presence check current all shows using global updates if detected display them proposed take place disable callable url realized possibility obtaining full strm posters fan art progress etc use feature necessary create into that call playing file with during playback available data episode store position watched status enable settings want receive currently movie but do not storing increase load processor control option there no change previously created simple by restore items lt prev next gt ", "");
   this[database_length++] = new SearchPage("addtolib/sred-mp3.html", "XXTREP: ADD TO Lib - More information", "xxtrep add to lib more information other actions show all exists tv shows displays list of added via when you select the he becomes current re index rescan for restore inner table links allowing define from source link or title lost episodes in event accidental deletion rename change type url open allows go folder replace already on actual useful case within advanced season with settings nbsp stable operation physically remove use tools this lt prev next gt ", "");
   this[database_length++] = new SearchPage("addtolib/addtolib-faq.html", "XXTREP: ADD TO Lib - F.A.Q.", "xxtrep add to lib translation suggestions pull nbsp requests supported platforms how install code borrowing contacts what is kodi? problem with posters on aeon mq6 view github quick answers search copyright by taifxxthis program free software you can redistribute it and or modify under the terms of gnu general public license as published foundation either version at your option any later this distributed in hope that will be useful but without warranty even implied merchantability fitness for particular purpose see more details http www org licenses problems ons from kodi repository taifxx download language russian home about information faq forums xbmc ru tv downloads ", "");
   this[database_length++] = new SearchPage("addtolib/sred-aeon.html", "XXTREP: ADD TO Lib - F.A.Q.", "xxtrep add to lib the problem is that aeon mq6 taken poster exclusively from fanart in on transferring listitem element which plays setresolvedurl function kodi there small bug regarding ignores setart thus make see posters only by making adjustments skin code file nbsp addons aeonmq6 includesvariables xmlblock lt variable name quot value thumbfullscreen gt condition isempty player art thumb info it after other before closing block lazy do now fixed xml version with ", "");
   this[database_length++] = new SearchPage("addtolib/addtolib-index.html", "XXTREP: ADD TO Lib", "xxtrep add to lib translation suggestions pull nbsp requests supported platforms how install code borrowing contacts what is kodi? problem with posters on aeon mq6 view github quick answers search copyright by taifxxthis program free software you can redistribute it and or modify under the terms of gnu general public license as published foundation either version at your option any later this distributed in hope that will be useful but without warranty even implied merchantability fitness for particular purpose see more details http www org licenses about information ons from kodi repository taifxx download language russian home faq forums xbmc ru tv downloads ", "");
   this[database_length++] = new SearchPage("RU/index.html.html", "Безымянная страница", "Безымянная страница ", "");
   this[database_length++] = new SearchPage("index.html", "XXTREP", "xxtrep ", "");
   return this;
}
